// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQNlgBw6eErfwwyKWdkCernqP_ziTj-I',
    appId: '1:591732752633:web:ffb48cef68f10e620fa228',
    messagingSenderId: '591732752633',
    projectId: 'rsh-study',
    authDomain: 'rsh-study.firebaseapp.com',
    storageBucket: 'rsh-study.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_P1jxLbHQ6nyt4jy4QVSgJ-Wf0IB4ME',
    appId: '1:591732752633:android:b3a35fb5547975c00fa228',
    messagingSenderId: '591732752633',
    projectId: 'rsh-study',
    storageBucket: 'rsh-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGuqpvGDi--krVbVtkfmmW5ZpmKefzizU',
    appId: '1:591732752633:ios:b969bac9d788e94b0fa228',
    messagingSenderId: '591732752633',
    projectId: 'rsh-study',
    storageBucket: 'rsh-study.appspot.com',
    iosClientId: '591732752633-ugc7o36rck7q74orhn69gcr15te3bg0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.twezhinawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGuqpvGDi--krVbVtkfmmW5ZpmKefzizU',
    appId: '1:591732752633:ios:b969bac9d788e94b0fa228',
    messagingSenderId: '591732752633',
    projectId: 'rsh-study',
    storageBucket: 'rsh-study.appspot.com',
    iosClientId: '591732752633-ugc7o36rck7q74orhn69gcr15te3bg0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.twezhinawa',
  );
}
